on: 
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Or a self-hosted runner if deploying to a private network
    env:
      CI: false # Sets CI to false for all steps in this job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install Dependencies
        run: npm ci # Use npm ci for clean installations in CI environments

      - name: Build Application
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master # Or a similar action for your deployment method
        with:
          server: tessanewbacher.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/ # Or your React build output directory (e.g., ./dist/)
          remote-dir: public_html/ # The target directory on cPanel